name: CI Nihar
repoFullName: Vanshiljain-Vanshiljain/cicircle
on:
  push:
    branches:
      - main

jobs:
  run-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version:
            ${{ matrix.node-version }}
           
      - name: npm Install
        run: npm install 
      
      - name: Firebase tools setup
        run:  npm install -g firebase-tools
        
      - name: Production Build
        run: npm run build
      
      - name: Production server
        run: firebase deploy --token '1//0gULYX7V6H6X2CgYIARAAGBASNwF-L9IrI93CK2X2lioDI82felcXrgqG7TPqLsYMtH3M6QZ5y9sT_GwdHrc-DSQCFEPiNEoH51Y'