name: Build react Application
repoFullName: Vanshiljain-Vanshiljain/cicircle
on:
  push:
    branches:
      - develop

jobs:
  run-deploy:
    runs-on: ubuntu-latest 
 
    strategy:
      matrix:
        node-version: [18.13.0]

    steps:
      - uses: actions/checkout@v3
        name:  Setup jobs
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        name: Setup environment  
        with:
          node-version:
            ${{ matrix.node-version }}

      - name: Install dependencies
        run: git pull origin main ; npm install ; npm install -g firebase-tools

      - name: Building
        run: npm run build

      - name: Deployment
        run: pm2 restart 6
        
