xzzxc  zzxcxdddcddsdxd  cccxx==cccxzcdcddczcxfcdddxcxcxname: CI/szssdzxx c dc
d
on:zz
  push:dc
    branche
      - main[;

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        npm install

    - name: Run Tests
      run: |
        npm test

    - name: Build
      run: |;
        npm run build

    # Add this step to upload logs as an artifactass
    - name: Upload Logs
      uses: actions/upload-artifact@v2
      with:
        name: build-logs
        path: |
          C:/Users/LENOVO/Desktop/cicircle/logs
          
# Add a new workflow to fetch the logs
jobs:
  fetch-logs:
    runs-on: ubuntu-latest

    steps:
    - name: Download Logs
      uses: actions/download-artifact@v2
      with:
        name: build-logs
        path: logs  # Specify the directory where you want to download the logs
